services:
  - type: web
    name: tg-casino-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_URL
        sync: false
      - key: BOT_DB_PATH
        value: bot.db
